# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc7f446676d21f46815cccd79840c6c13c30f4c3f4d096cf48778e6b15d0d20a60ad2d15e1319adb62a4134fd532154cff4d42565dfea5d2d6a15e7833b97c00

test:
  secret_key_base: 850ddcc0c71dcb83536daf29d430377da682da815f76b26023671042f20fc604c88aa26d6b72b57fedf5bef2249ca4e0523e662af89590fb00af500066f41555

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
